\c :mosipdbname

GRANT CONNECT
   ON DATABASE :mosipdbname
   TO :dbuname;

GRANT USAGE
   ON SCHEMA credential
   TO :dbuname;

GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES
      ON ALL TABLES IN SCHEMA credential
          TO :dbuname;

ALTER DEFAULT PRIVILEGES IN SCHEMA credential
	GRANT SELECT,INSERT,UPDATE,DELETE,REFERENCES ON TABLES TO :dbuname;
