\c mosip_idrepo

\ir ddl/idrepo-uin.sql
\ir ddl/idrepo-uin_h.sql
\ir ddl/idrepo-uin_document.sql
\ir ddl/idrepo-uin_document_h.sql
\ir ddl/idrepo-uin_biometric.sql
\ir ddl/idrepo-uin_biometric_h.sql
\ir ddl/idrepo-uin_hash_salt.sql
\ir ddl/idrepo-uin_encrypt_salt.sql
\ir ddl/idrepo-uin_auth_lock.sql
\ir ddl/idrepo-fk.sql
\ir ddl/idrepo-credential_request_status.sql
\ir ddl/idrepo-uin_biometric_draft.sql
\ir ddl/idrepo-uin_draft.sql
\ir ddl/idrepo-uin_document_draft.sql
\ir ddl/idrepo-anonymous_profile.sql
\ir ddl/idrepo-channel_info.sql
\ir ddl/idrepo-identity_update_count_tracker.sql
