openapi: 3.0.1
info:
  title: MOSIP Credential Service API
  description: >
    This API provides endpoints to fetch credential types and issue digital credentials
    as part of the MOSIP identity management ecosystem.
  version: '1.0'
  contact:
    name: MOSIP Development Team
    email: dev@mosip.io
    url: https://www.mosip.io
  termsOfService: https://www.mosip.io/terms
  license:
    name: MOSIP License
    url: 'https://docs.mosip.io/platform/license'

servers:
  - url: 'https://api-internal.collab.mosip.net/v1/credentialservice/'
    description: Internal credential service API base path

tags:
  - name: Credential Types
    description: Fetch available credential types
  - name: Credential Issuance
    description: Create and issue a digital credential

paths:
  /types:
    get:
      tags:
        - Credential Types
      summary: Get credential types
      description: >
        Retrieve the list of credential types supported by the credential issuance service.
      operationId: getCredentialTypes
      responses:
        '200':
          description: Credential types retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CredentialTypeResponse'
        '400':
          description: Unable to fetch credential types
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /issue:
    post:
      tags:
        - Credential Issuance
      summary: Issue new credential
      description: >
        Issues one or more credentials based on the provided template and recipient information.
      operationId: issueCredential
      requestBody:
        required: true
        content:
          application/json:
            example:
              id: "10011100010000420250226133223"
              credentialType: "auth"
              requestId: "4aa31268-3337-45b8-8472-ee689875077f"
              issuer: "mpartner-default-auth"
              recepiant: "IDA"
              user: ""
              encrypt: false
              encryptionKey: null
              sharableAttributes: []
              additionalData: {}
      responses:
        '200':
          description: Credential(s) issued successfully
          content:
            application/json:
              example:
                - id: "10011100010000420250226133223"
                  credentialType: "auth"
                  requestId: "4aa31268-3337-45b8-8472-ee689875077f"
                  issuer: "mpartner-default-auth"
                  recepiant: "IDA"
                  user: ""
                  encrypt: false
                  encryptionKey: null
                  sharableAttributes: []
                  additionalData: {}
components:
  responses:
    UnauthorizedError:
      description: Unauthorized
    ForbiddenError:
      description: Forbidden
    NotFoundError:
      description: Not Found
    InternalServerError:
      description: Internal Server Error

  schemas:
    CredentialTypeResponse:
      type: object
      properties:
        credentialTypes:
          type: array
          items:
            $ref: '#/components/schemas/Type'
      example:
        credentialTypes:
          - id: HEALTH_CERT
            name: Health Certificate
            description: COVID-19 vaccination certificate
            issuers:
              - code: MOHFW
                name: Ministry of Health

    Issuer:
      type: object
      properties:
        code:
          type: string
        name:
          type: string

    Type:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        issuers:
          type: array
          items:
            $ref: '#/components/schemas/Issuer'

    CredentialIssueRequest:
      type: object
      properties:
        id:
          type: string
        credentialType:
          type: string
        requestId:
          type: string
        issuer:
          type: string
        recepiant:
          type: string
        user:
          type: string
        encrypt:
          type: boolean
        encryptionKey:
          type: string
        sharableAttributes:
          type: array
          items:
            type: string
        additionalData:
          type: object
          additionalProperties:
            type: object

    CredentialIssueResponse:
      type: object
      properties:
        id:
          type: string
        version:
          type: string
        responsetime:
          type: string
        response:
          $ref: '#/components/schemas/CredentialServiceResponse'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorDTO'

    CredentialServiceResponse:
      type: object
      properties:
        status:
          type: string
        credentialId:
          type: string
        issuanceDate:
          type: string
          format: date-time
        signature:
          type: string
        dataShareUrl:
          type: string

    ErrorDTO:
      type: object
      properties:
        errorCode:
          type: string
        message:
          type: string
