logging.level.root=INFO

mosip.api.public.host=api.${subdomain}.mosip.net
mosip.api.internal.host=api-internal.${subdomain}.mosip.net
mosip.api.internal.url=https://${mosip.api.internal.host}
mosip.esignet.mosipid.host=esignet.${subdomain}.mosip.net
keycloak.internal.url=https://iam.${subdomain}.mosip.net
keycloak.external.host=https://iam.${subdomain}.mosip.net
keycloak.external.url=https://iam.${subdomain}.mosip.net
mosip.resident.host=resident.${subdomain}.mosip.net
mosip.idp.host=idp.${subdomain}.mosip.net
mosip.prereg.host=prereg.${subdomain}.mosip.net
mosip.esignet.host=esignet.${subdomain}.mosip.net

javax.persistence.jdbc.user=postgres
mosip.resident.database.hostname=${subdomain}.mosip.net
mosip.idrepo.db.url=${subdomain}.mosip.net
mosip.credential.service.database.hostname=${subdomain}.mosip.net

spring.jpa.hibernate.ddl-auto=none
hibernate.hbm2ddl.auto=none
hibernate.show_sql=true
spring.jpa.show-sql=true
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
javax.persistence.jdbc.driver=org.postgresql.Driver
hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
hibernate.jdbc.lob.non_contextual_creation = true


s3.accesskey={cipher}e16f132dc80ad5043acb6c2173c95be217ee5f5246a589ca58d5f75fa0a9d63d
s3.secretkey={cipher}e419b23e688cc23991001afddbda206d42f7df5090c65f3566be7651c90128c1
s3.region=
s3.pretext.value=${subdomain}-


## Common properties used across different modules
mosipbox.public.url=${mosip.api.internal.url}
mosip.kernel.authmanager.url=${mosipbox.public.url}
mosip.kernel.masterdata.url=${mosipbox.public.url}
mosip.kernel.keymanager.url=${mosipbox.public.url}
mosip.kernel.auditmanager.url=${mosipbox.public.url}
mosip.kernel.notification.url=${mosipbox.public.url}
mosip.kernel.idgenerator.url=${mosipbox.public.url}
mosip.kernel.otpmanager.url=${mosipbox.public.url}
mosip.kernel.syncdata.url=${mosipbox.public.url}
mosip.kernel.pridgenerator.url=${mosipbox.public.url}
mosip.kernel.ridgenerator.url=${mosipbox.public.url}
mosip.idrepo.identity.url=${mosipbox.public.url}
mosip.idrepo.vid.url=${mosipbox.public.url}
mosip.admin.hotlist.url=${mosipbox.public.url}
mosip.pms.policymanager.url=${mosipbox.public.url}
mosip.pms.partnermanager.url=${mosipbox.public.url}
mosip.idrepo.credrequest.generator.url=${mosipbox.public.url}
mosip.idrepo.credential.service.url=${mosipbox.public.url}
mosip.datashare.url=${mosipbox.public.url}
mosip.mock.biosdk.url=${mosipbox.public.url}
mosip.regproc.workflow.url=${mosipbox.public.url}
mosip.regproc.status.service.url=${mosipbox.public.url}
mosip.regproc.transaction.service.url=${mosipbox.public.url}
mosip.packet.receiver.url=${mosipbox.public.url}
mosip.websub.url=${mosipbox.public.url}
mosip.file.server.url=${mosipbox.public.url}
mosip.ida.internal.url=${mosipbox.public.url}
mosip.ida.auth.url=${mosipbox.public.url}
mosip.ida.otp.url=${mosipbox.public.url}
mosip.resident.url=${mosipbox.public.url}
mosip.digitalcard.service.url=${mosipbox.public.url}
mosip.esignet.service.url=${mosipbox.public.url}

mosip.admin.service.url=${mosipbox.public.url}
mosip.admin.ui.url=${mosipbox.public.url}
mosip.pms.ui.url=${mosipbox.public.url}
mosip.regproc.biosdk.url=${mosipbox.public.url}
mosip.idrepo.biosdk.url=${mosipbox.public.url}
mosip.consolidator.url=${mosipbox.public.url}
mosip.artifactory.url=${mosipbox.public.url}
#object.store.s3.url=https://minio.${subdomain}.mosip.net:9000

softhsm.kernel.security.pin=123

softhsm.ida.security.pin=57261711

#db.dbuser.password =OfUQvf4kUK
ida.websub.credential.issue.callback.secret=BsMobuD53XyTJvir
mosip.ida.database.hostname=${subdomain}.mosip.net

### Keymanager service
##Type of keystore, Supported Types: PKCS11, PKCS12, Offline, JCE
#mosip.kernel.keymanager.hsm.keystore-type=OFFLINE
### For PKCS11 provide Path of config file.
### For PKCS12 keystore type provide the p12/pfx file path. P12 file will be created internally so provide only file path & file name.
### For Offline & JCE property can be left blank, specified value will be ignored.
#mosip.kernel.keymanager.hsm.config-path=
#mosip.kernel.keymanager.hsm.keystore-pass=${softhsm.kernel.security.pin}
# Passkey of keystore for PKCS11, PKCS12
# For Offline & JCE proer can be left blank. JCE password use other JCE specific properties.

#mosip.kernel.keymanager.hsm.config-path=C:/Users/kames/myp12.p12
#mosip.kernel.keymanager.hsm.keystore-type=PKCS12
#mosip.kernel.keymanager.hsm.keystore-pass=kamesh

mosip.ida.kyc.token.secret=RHAzSkNNYkU4ajhMbXNtSEtBU1dHbWpWNzcyZnNCcmw=
ida.websub.authtype.callback.secret=iZONE5UnKUbvsGDW
ida.websub.ca.certificate.callback.secret=WWg1wzjsVFgiYhCh
ida.websub.hotlist.callback.secret=3ddV96PYBmjum3oM
ida.websub.partner.service.callback.secret=8VbNvrziy19zEHGI
ida.websub.masterdata.templates.callback.secret=Bp5KMe8kKdBQJ0BZ
ida.websub.masterdata.titles.callback.secret=hkLlzwucBe4WNaEn

spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

smtp.host=