#IDRepo credential request generator authentication details
mosip.idrepo.credential-req-generator.auth.client-id=mosip-idrepo-client
mosip.idrepo.credential-req-generator.auth.secret-key=${mosip.idrepo.client.secret}
mosip.idrepo.credential-req-generator.auth.app-id=idrepo

#------------------------- Kernel Auth Adapter self token generator properties ----------------------------#
mosip.iam.adapter.clientid.credential-request=${mosip.idrepo.credential-req-generator.auth.client-id}
mosip.iam.adapter.clientsecret.credential-request=${mosip.idrepo.credential-req-generator.auth.secret-key}
mosip.iam.adapter.appid.credential-request=${mosip.idrepo.credential-req-generator.auth.app-id}

mosip.auth.filter_disable=true
hibernate.hbm2ddl.auto=none
hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
hibernate.jdbc.lob.non_contextual_creation = true
