\c mosip_idmap 

GRANT CONNECT
   ON DATABASE mosip_idmap
   TO idmapuser;

GRANT USAGE
   ON SCHEMA idmap
   TO idmapuser;

GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES
   ON ALL TABLES IN SCHEMA idmap
   TO idmapuser;

ALTER DEFAULT PRIVILEGES IN SCHEMA idmap 
	GRANT SELECT,INSERT,UPDATE,DELETE,REFERENCES ON TABLES TO idmapuser;

