\c :mosipdbname

REASSIGN OWNED BY sysadmin TO postgres;

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA credential FROM :dbuname;

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA credential FROM sysadmin;

GRANT SELECT, INSERT, TRUNCATE, REFERENCES, UPDATE, DELETE ON ALL TABLES IN SCHEMA credential TO :dbuname;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA credential TO postgres;