ALTER DATABASE mosip_idmap OWNER TO postgres;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA idmap TO postgres;

REVOKE ALL PRIVILEGES ON DATABASE mosip_idmap FROM idmapuser, sysadmin;

GRANT SELECT, INSERT, TRUNCATE, REFERENCES, UPDATE, DELETE ON ALL TABLES IN SCHEMA idmap TO idmapuser;