\c mosip_idmap

REASSIGN OWNED BY sysadmin TO postgres;

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA idmap FROM idmapuser;

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA idmap FROM sysadmin;

GRANT SELECT, INSERT, TRUNCATE, REFERENCES, UPDATE, DELETE ON ALL TABLES IN SCHEMA idmap TO idmapuser;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA idmap TO postgres;